### ISSUE TITLE
请教一下 公众号模板消息发送

### ISSUE THREAD

**Issue by andy236726493** [pengxuxu/hyperf-easywechat6#1]
$app       = EasyWechat::officialAccount(); 
$result     = $app->template_message->send([
                                                'touser' => 'xxx2Yc-nvKbQTvZrc',
                                                'template_id' => 'xxxxAHtUg2mAn7_RfYZJRSiX3-pTM',
                                                'url' => 'http://xxx.com/',
                                                'data' => [
                                                    'first'    => array('value' => '尊敬的XXX,您好!', 'color' => "#FF0000"),
                                                    'keyword1' => array('value' => '公司', 'color' => '#FF0000'),
                                                    'keyword2' => array('value' => '12345', 'color' => '#FF0000'),
                                                    'keyword3' => array('value' => '100元', 'color' => '#FF0000'),
                                                    'keyword4' => array('value' => '2023年2月5日 18:36', 'color' => '#FF0000'),
                                                    'remark'   => array('value' => '感谢您对持！', 'color' => '#FF0000')
                                                ]
        ]);

提示  template_message  没有这个方法

**Comment by pengxuxu** [comment]
你这个调用是easywechat4和5的用法，easywechat6只封装最基础的加密和请求，具体请看easywechat6的文档







------------------ 原始邮件 ------------------
发件人: andy ***@***.***&gt;
发送时间: 2023年2月2日 12:01
收件人: pengxuxu/hyperf-easywechat6 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [pengxuxu/hyperf-easywechat6] 请教一下 公众号模板消息发送 (Issue #1)





 
$app       = EasyWechat::officialAccount();
 $result     = $app-&gt;template_message-&gt;send([
 'touser' =&gt; 'xxx2Yc-nvKbQTvZrc',
 'template_id' =&gt; 'xxxxAHtUg2mAn7_RfYZJRSiX3-pTM',
 'url' =&gt; 'http://xxx.com/',
 'data' =&gt; [
 'first'    =&gt; array('value' =&gt; '尊敬的XXX,您好!', 'color' =&gt; "#FF0000"),
 'keyword1' =&gt; array('value' =&gt; '公司', 'color' =&gt; '#FF0000'),
 'keyword2' =&gt; array('value' =&gt; '12345', 'color' =&gt; '#FF0000'),
 'keyword3' =&gt; array('value' =&gt; '100元', 'color' =&gt; '#FF0000'),
 'keyword4' =&gt; array('value' =&gt; '2023年2月5日 18:36', 'color' =&gt; '#FF0000'),
 'remark'   =&gt; array('value' =&gt; '感谢您对持！', 'color' =&gt; '#FF0000')
 ]
 ]);
 
提示  template_message  没有这个方法
