### ISSUE TITLE
调用接口报错

### ISSUE THREAD

**Issue by QQOQ** [pengxuxu/hyperf-easywechat6#3]
```
$api = $app->getClient();
        $response = $api->postJson('/cgi-bin/menu/create', [
            [
                "type"=> "view",
                "name"=> "xxx",
                "key"=> "https://xxx.com"
            ]
        ]);
```
会出现下面这个错误
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes) in /home/www/xxx/runtime/container/proxy/App_Controller_WechatController.proxy.php on line 41
[2023-05-22 23:39:03 *360474.3] ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes) in /home/www/xxx/runtime/container/proxy/App_Controller_WechatController.proxy.php on line 41
[2023-05-22 23:39:03 $360466.0] WARNING Server::check_worker_exit_status(): worker(pid=360474, id=3) abnormal exit, status=255, signal=0

**Comment by pengxuxu** [comment]
> ```
> $api = $app->getClient();
>         $response = $api->postJson('/cgi-bin/menu/create', [
>             [
>                 "type"=> "view",
>                 "name"=> "xxx",
>                 "key"=> "https://xxx.com"
>             ]
>         ]);
> ```
> 
> 会出现下面这个错误 Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes) in /home/www/xxx/runtime/container/proxy/App_Controller_WechatController.proxy.php on line 41 [2023-05-22 23:39:03 *360474.3] ERROR php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 803213312 bytes) in /home/www/xxx/runtime/container/proxy/App_Controller_WechatController.proxy.php on line 41 [2023-05-22 23:39:03 $360466.0] WARNING Server::check_worker_exit_status(): worker(pid=360474, id=3) abnormal exit, status=255, signal=0

问题描述环境不清，建议好好复查
