### ISSUE TITLE
ClassMap如何替换呢？

### ISSUE THREAD

**Issue by gozhhu** [pengxuxu/hyperf-easywechat6#5]
请问src下有个ClassMap这么放就行吗？还是需要自己手动改下composer.json? 谢谢

我的报错： PHP Fatal error:  Trait "EasyWeChat\Kernel\Traits\InteractWithHttpClient" not found in /opt/www/vendor/w7corp/easywechat/src/Pay/Application.php on line 17

**Comment by pengxuxu** [comment]
composer.json文件不需要管，hyperf在启动时会扫描extra，进而再加载初始化里面的ConfigProvider，用现在的客户端请求替换掉easywechat，你的报错应该是easywechat包问题，建议重装。每个Application都有use InteractWithHttpClient，你可以看easywechat的源码，你这个报错是找不到，明显和源码不符。
