### ISSUE TITLE
示例代码可以验证token,  被动消息却不回复（谢谢关注），是要做特殊处理吗

### ISSUE THREAD

**Issue by yuzihui** [pengxuxu/hyperf-easywechat6#6]
![image](https://github.com/user-attachments/assets/fa73030d-6683-4901-b129-b2f8722a8271)

**Comment by pengxuxu** [comment]
return “谢谢关注”，easywechat6包内部会做处理，转换为微信回复里文本格式，这个不影响，请排查其他问题。

**Comment by yuzihui** [comment]
谢谢 已解决！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月11日(星期一) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pengxuxu/hyperf-easywechat6] 示例代码可以验证token,  被动消息却不回复（谢谢关注），是要做特殊处理吗 (Issue #6)














 
return “谢谢关注”，easywechat6包内部会做处理，转换为微信回复里文本格式，这个不影响，请排查其他问题。
